# Generated by Django 6.0.3 on 2026-04-06 02:19

from django.db import migrations


def create_default_manager(apps, schema_editor):
    """
    Cria grupos padrão (Manager, Editor, Viewer) e um usuário de desenvolvimento
    com permissões de Manager para testes.
    """
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')
    
    manager_group, _ = Group.objects.get_or_create(name='Manager')
    editor_group, _ = Group.objects.get_or_create(name='Editor')
    viewer_group, _ = Group.objects.get_or_create(name='Viewer')
        
    if not User.objects.filter(username='developer').exists():
        user = User.objects.create_user(
            username='developer',
            email='developer@mber.com',
            password='dev123',
            first_name='Developer',
            last_name='User',
            is_staff=True
        )
        user.groups.add(manager_group)
        print("✓ Usuário de desenvolvimento criado: developer / dev123 (grupo Manager)")


def reverse_default_manager(apps, schema_editor):
    """
    Remove o usuário de desenvolvimento padrão e os grupos.
    """
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')
    
    User.objects.filter(username='developer').delete()
    Group.objects.filter(name__in=['Manager', 'Editor', 'Viewer']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '__latest__'),
    ]

    operations = [
        migrations.RunPython(create_default_manager, reverse_default_manager),
    ]
