services:
  web:
    build: ./backend
    command: sh -c "python manage.py migrate && python manage.py setup_permissions && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - PORT=8000

  frontend: # React
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    ports:
      - "3000:3000" # Você acessará o site em http://localhost:3000
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_API_URL=http://localhost:8000/api/
