version: '3.8'

services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py setup_permissions && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - PORT=8000

  frontend: # React
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules # Evita que o Docker sobrescreva os pacotes instalados
    ports:
      - "3000:5173" # Você acessará o site em http://localhost:3000
    environment:
      - VITE_API_URL=http://localhost:8000/api/
