# Generated by Django 6.0.3 on 2026-04-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('side_dish', models.TextField(blank=True, verbose_name='Side Dish')),
                ('image', models.URLField(blank=True, max_length=500, verbose_name='Image URL')),
                ('category', models.CharField(choices=[('main_dish', 'Main Dish'), ('others', 'Others')], default='main_dish', max_length=20, verbose_name='Category')),
                ('lunch_box_price_small', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lunch Box Price (Small)')),
                ('lunch_box_price_medium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lunch Box Price (Medium)')),
                ('lunch_box_price_large', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lunch Box Price (Large)')),
                ('daily_plate_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Daily Plate Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['name'],
            },
        ),
    ]
