# Generated by Django 6.0.3 on 2026-04-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='weekdays',
            field=models.JSONField(blank=True, default=list, help_text='List of weekdays when this item is available. Empty list means available every day.', verbose_name='Available Weekdays'),
        ),
    ]
