# Generated by Django 6.0.3 on 2026-04-06 02:58

from django.db import migrations
from decimal import Decimal


def create_initial_menu_items(apps, schema_editor):
    MenuItem = apps.get_model('menu', 'MenuItem')
    
    MenuItem.objects.create(
        name='Feijoada Completa',
        side_dish='Arroz branco, farofa, couve refogada, laranja',
        image='https://images.unsplash.com/photo-1628294895950-9805252327bc',
        category='main_dish',
        lunch_box_price_small=Decimal('18.00'),
        lunch_box_price_medium=Decimal('22.00'),
        lunch_box_price_large=Decimal('26.00'),
        weekdays=['wednesday', 'saturday'],
        is_active=True
    )
    
    MenuItem.objects.create(
        name='Strogonoff de Frango',
        side_dish='Arroz branco, batata palha',
        image='https://images.unsplash.com/photo-1604908176997-125f25cc6f3d',
        category='main_dish',
        lunch_box_price_small=Decimal('16.00'),
        lunch_box_price_medium=Decimal('20.00'),
        lunch_box_price_large=Decimal('24.00'),
        daily_plate_price=Decimal('28.00'),
        weekdays=[],
        is_active=True
    )
    
    MenuItem.objects.create(
        name='Picanha Grelhada',
        side_dish='Arroz, feijão tropeiro, vinagrete, farofa',
        image='https://images.unsplash.com/photo-1558030006-450675393462',
        category='main_dish',
        lunch_box_price_small=Decimal('22.00'),
        lunch_box_price_medium=Decimal('28.00'),
        lunch_box_price_large=Decimal('34.00'),
        daily_plate_price=Decimal('38.00'),
        weekdays=['friday', 'saturday', 'sunday'],
        is_active=True
    )


def remove_initial_menu_items(apps, schema_editor):
    MenuItem = apps.get_model('menu', 'MenuItem')
    MenuItem.objects.filter(
        name__in=[
            'Feijoada Completa',
            'Strogonoff de Frango',
            'Picanha Grelhada'
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_weekdays'),
    ]

    operations = [
        migrations.RunPython(create_initial_menu_items, remove_initial_menu_items),
    ]
