# Generated by Django 6.0.3 on 2026-04-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('dishDay', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('almoco', 'Almoço'), ('porcoes', 'Porções'), ('bebidas', 'Bebidas')], max_length=50)),
            ],
        ),
    ]
