# Generated by Django

from django.db import migrations


def create_initial_categories(apps, schema_editor):
    Category = apps.get_model('menu', 'Category')
    
    categories = [
        {'code': 'prato-do-dia', 'name': 'Prato do Dia', 'is_active': True},
        {'code': 'bebidas', 'name': 'Bebidas', 'is_active': True},
    ]
    
    for cat_data in categories:
        Category.objects.get_or_create(
            code=cat_data['code'],
            defaults=cat_data
        )


def reverse_categories(apps, schema_editor):
    Category = apps.get_model('menu', 'Category')
    Category.objects.filter(
        code__in=['prato-do-dia', 'bebidas']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_category_remove_menuitem_category_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_categories, reverse_categories),
    ]
