# Generated by Django

from django.db import migrations


def associate_items_to_prato_do_dia(apps, schema_editor):
    MenuItem = apps.get_model('menu', 'MenuItem')
    Category = apps.get_model('menu', 'Category')
    
    # Buscar a categoria "prato-do-dia"
    try:
        prato_do_dia = Category.objects.get(code='prato-do-dia')
        
        # Associar todos os itens de menu à categoria "prato-do-dia"
        for item in MenuItem.objects.all():
            item.categories.add(prato_do_dia)
            
    except Category.DoesNotExist:
        pass


def reverse_association(apps, schema_editor):
    MenuItem = apps.get_model('menu', 'MenuItem')
    Category = apps.get_model('menu', 'Category')
    
    try:
        prato_do_dia = Category.objects.get(code='prato-do-dia')
        
        # Remover associação de todos os itens
        for item in MenuItem.objects.all():
            item.categories.remove(prato_do_dia)
            
    except Category.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_add_initial_categories'),
    ]

    operations = [
        migrations.RunPython(associate_items_to_prato_do_dia, reverse_association),
    ]
