# Generated by Django 6.0.3 on 2026-04-22 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_associate_menu_items_to_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('is_open', models.BooleanField(default=True, verbose_name='Is Open')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='menu.menuitem', verbose_name='Menu Item')),
            ],
            options={
                'verbose_name': 'Menu Item Schedule',
                'verbose_name_plural': 'Menu Item Schedules',
                'ordering': ['date'],
            },
        ),
    ]
