# Generated by Django 6.0.3 on 2026-04-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_menuitemschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemschedule',
            name='daily_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Daily Price Override'),
        ),
    ]
